DE_aws_dbt_snowflake_project:
  outputs:
    dev:
      account: RGAHAXG-CBC09086
      database: AIRBNB
      password: NagendraSaiManne1@
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: NAGENDRA1711
      warehouse: COMPUTE_WH
  target: dev
